#!/bin/bash

wally=amundmo@gmail.com
thrperinst=6
emails=x

docker run -itd -e USERNAME=$wally -e THREADS=$thrperinst --cpuset-cpus="1,2,5,7,9,10,13,15" condevtec/xmr-miner-cpu 

docker run -itd -e USERNAME=$wally -e THREADS=$thrperinst --cpuset-cpus="0,3,4,6,8,11,12,14" condevtec/xmr-miner-cpu
